mod 'puppet-nginx', '1.0.0'
mod 'puppetlabs-concat'
mod 'puppetlabs-stdlib'
mod 'puppetlabs-translate'
mod 'samuelson/dockeragent'
#mod 'garethr/docker' 
mod 'puppetlabs/docker'
mod 'puppetlabs/apt'
mod 'puppetlabs/powershell'
mod 'puppetlabs/reboot'
mod 'puppetlabs/pwshlib'